In [1]:
import pandas as pd
from pandas.api.types import CategoricalDtype
import numpy as np
pd.options.display.float_format = '{:,.2f}'.format
import os
from itertools import product
import app_rais.dicts_constants as dc
import app_rais.treat as treat

In [2]:
list_column_keep = dc.interest_columns_for_year(2018)

In [3]:
list_ufs=['AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MG','PA','PE','PR','RJ','RS','SC','SP']

In [4]:
%%time
treat.pretreat_2018(list_ufs=list_ufs)

AM2018.txt saved.
None
BA2018.txt already exists.
CE2018.txt already exists.
DF2018.txt already exists.
ES2018.txt already exists.
GO2018.txt already exists.
MG2018.txt already exists.
PA2018.txt already exists.
PE2018.txt already exists.
PR2018.txt already exists.
RJ2018.txt already exists.
RS2018.txt already exists.
SC2018.txt already exists.
SP2018.txt already exists.
Wall time: 1min

In [5]:
%%time
treat.original_to_treated_loop(
    ufs=['AM']
    , years=[2018]
)

AM2018.zip saved.
Wall time: 7.8 s

In [5]:
%%time
treat.original_to_treated_loop(
    ufs=['AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MG','PA','PE','PR','RJ','RS','SC','SP']
    , years=[2018]
)

AM2018.zip saved.
BA2018.zip saved.
CE2018.zip saved.
DF2018.zip saved.
ES2018.zip saved.
GO2018.zip saved.
MG2018.zip saved.
PA2018.zip saved.
PE2018.zip saved.
PR2018.zip saved.
RJ2018.zip saved.
RS2018.zip saved.
SC2018.zip saved.
SP2018.zip saved.
Wall time: 8min 54s

In [6]:
%%time
treat.load_save_rais_dataframe_loop(
    list_ufs=['AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MG','PA','PE','PR','RJ','RS','SC','SP']
    , list_years=[2018])

ufs_with_motropolises_2018 saved.
Wall time: 1min 49s

In [4]:
df = pd.read_csv('app_rais/data/rais_original/2018/AM2018.txt', encoding='Latin-1', sep=';', decimal=',', dtype=dc.dic_dtype)

In [6]:
pd.read_pickle('app_rais/data/rais_treated/2018/AM2018.zip')

,CBO Ocupação 2002,CNAE 2.0 Classe,CNAE 95 Classe,Faixa Etária,Faixa Remun Dezem (SM),Faixa Remun Média (SM),Escolaridade após 2005,Idade,Ind Simples,Município,...,Sexo Trabalhador,Tamanho Estabelecimento,Tipo Estab,Tipo Estab.1,IBGE Subsetor,territorio_tese,arranjo,knowledge_services,technology_industries,potec
0,514320,56201,55247,06,02,02,1,46,0,160030,...,01,7,01,CNPJ,13,NaN,Demais Municípios do Amapá,Less knowledge-intensive market services,Without Classification,Demais Ocupações
1,514225,77110,71102,07,NaN,03,1,53,0,160060,...,01,6,01,CNPJ,19,NaN,Demais Municípios do Amapá,Less knowledge-intensive market services,Without Classification,Demais Ocupações
2,513610,56112,55212,03,03,02,1,19,1,160030,...,01,3,01,CNPJ,21,NaN,Demais Municípios do Amapá,Less knowledge-intensive market services,Without Classification,Demais Ocupações
3,514325,10538,15431,03,05,03,1,22,0,160060,...,01,7,01,CNPJ,13,NaN,Demais Municípios do Amapá,Without Classification,Low-technology,Demais Ocupações
4,717020,81214,74705,05,03,02,1,33,1,160060,...,01,5,01,CNPJ,21,NaN,Demais Municípios do Amapá,Less knowledge-intensive market services,Without Classification,Demais Ocupações
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132238,234405,85317,80314,06,10,09,11,46,0,160030,...,02,10,01,CNPJ,23,NaN,Demais Municípios do Amapá,Other knowledge-intensive services,Without Classification,Demais Ocupações
132239,231205,85317,80314,07,12,11,11,51,0,160030,...,02,10,01,CNPJ,23,NaN,Demais Municípios do Amapá,Other knowledge-intensive services,Without Classification,Demais Ocupações
132240,234624,85317,80314,07,12,11,11,54,0,160030,...,02,10,01,CNPJ,23,NaN,Demais Municípios do Amapá,Other knowledge-intensive services,Without Classification,Demais Ocupações
132241,234415,85317,80314,07,12,10,11,52,0,160030,...,02,10,01,CNPJ,23,NaN,Demais Municípios do Amapá,Other knowledge-intensive services,Without Classification,Demais Ocupações
132242,223505,84116,75116,07,10,09,11,58,0,160030,...,02,8,01,CNPJ,24,NaN,Demais Municípios do Amapá,Other knowledge-intensive services,Without Classification,Demais Ocupações

In [2]:
df = pd.read_pickle('app_rais/data/rais_treated/2000/PR2000.zip')